apiVersion: v1
kind: Service
metadata:
  name: sqlite
  labels:
    app: sqlite
spec:
  clusterIP: None
  selector:
    app: sqlite
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
