mysql:
  image: mysql
  tag: 8.0
  pullPolicy: IfNotPresent

  replicas: 3

  rootPassword: "set-root-password"
  database: "myapp_db"
  username: "set-username"
  password: "set-password"

storage:
  size: 1Gi
  storageClassName: standard

service:
  type: ClusterIP
  port: 3306

resources:
  requests:
    memory: 128Mi
    cpu: 128m
  limits:
    memory: 256Mi
    cpu: 512m

nodeSelector: {}
tolerations: []