apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/

patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: orderflow-app
    patch: |-
      - op: replace
        path: /metadata/name
        value: orderflow-app
      - op: replace
        path: /spec/source/path
        value: orderflow/overlays/prod
      - op: replace
        path: /spec/destination/namespace
        value: orderflow
      - op: remove
        path: /spec/syncPolicy/automated
      - op: add
        path: /metadata/labels
        value:
          environment: prod
          managed-by: kustomize
