apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-orderflow
  labels:
    app: orderflow
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: orderflow
  template:
    metadata:
      labels:
        app: orderflow
    spec:
      containers:
        - name: orderflow
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
