apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/

patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: orderflow-app
    patch: |-
      - op: replace
        path: /metadata/name
        value: orderflow-app-staging
      - op: replace
        path: /spec/source/path
        value: orderflow/overlays/staging
      - op: replace
        path: /spec/destination/namespace
        value: orderflow-staging
      - op: add
        path: /metadata/labels
        value:
          environment: staging
          managed-by: kustomize
